DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  seller_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  thumbnail_photo_url VARCHAR(255) NOT NULL,
  category_name VARCHAR(255) NOT NULL,
  price INTEGER  NOT NULL DEFAULT 0,
  stock INTEGER  NOT NULL DEFAULT 0,
  promotion BOOLEAN NOT NULL DEFAULT FALSE,
  sold BOOLEAN NOT NULL DEFAULT FALSE

);